# Generated by Django 2.2.6 on 2019-10-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True, 'verbose_name': 'todo', 'verbose_name_plural': 'todoes'},
        ),
    ]
