# Generated by Django 2.2.6 on 2019-10-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'managed': True, 'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
